export const typeColors = {
    bug: 'border-emerald-500 dark:border-emerald-700 shadow-md shadow-emerald-900 hover:shadow-lg hover:shadow-emerald-900',
    dark: 'border-slate-500 dark:border-slate-700 shadow-md shadow-slate-900 hover:shadow-lg hover:shadow-slate-900',
    dragon: 'border-orange-400 dark:border-orange-600 shadow-md shadow-orange-900 hover:shadow-lg hover:shadow-orange-900',
    electric: 'border-yellow-200 dark:border-yellow-400 shadow-md shadow-yellow-900 hover:shadow-lg hover:shadow-yellow-900',
    fairy: 'border-pink-200 dark:border-pink-400 shadow-md shadow-pink-900 hover:shadow-lg hover:shadow-pink-900',
    fighting: 'border-amber-500 dark:border-amber-700 shadow-md shadow-amber-950 hover:shadow-lg hover:shadow-amber-950',
    fire: 'border-red-400 dark:border-red-600 shadow-md shadow-red-900 hover:shadow-lg hover:shadow-red-950',
    flying: 'border-sky-300 dark:border-sky-500 shadow-md shadow-sky-900 hover:shadow-lg hover:shadow-sky-900',
    ghost: 'border-violet-300 dark:border-violet-500 shadow-md shadow-violet-900 hover:shadow-lg hover:shadow-violet-900',
    grass: 'border-green-300 dark:border-green-500 shadow-md shadow-green-900 hover:shadow-lg hover:shadow-green-900',
    ground: 'border-yellow-500 dark:border-yellow-700 shadow-md shadow-yellow-950 hover:shadow-lg hover:shadow-yellow-950',
    ice: 'border-cyan-200 dark:border-cyan-300 shadow-md shadow-cyan-900 hover:shadow-xl hover:shadow-cyan-900',
    normal: 'border-neutral-300 dark:border-neutral-500 shadow-md shadow-neutral-900 hover:shadow-lg hover:shadow-neutral-900',
    poison: 'border-lime-400 dark:border-lime-600 shadow-md shadow-lime-900 hover:shadow-lg hover:shadow-lime-900',
    psychic: 'border-fuchsia-400 dark:border-fuchsia-600 shadow-md shadow-fuchsia-900 hover:shadow-lg hover:shadow-fuchsia-900',
    rock: 'border-stone-300 dark:border-stone-500 shadow-md shadow-stone-900 hover:shadow-lg hover:shadow-stone-900',
    steel: 'border-zinc-300 dark:border-zinc-500 shadow-md shadow-zinc-900 hover:shadow-lg hover:shadow-zinc-900',
    water: 'border-cyan-300 dark:border-cyan:500 shadow-md shadow-cyan-900 hover:shadow-lg hover:shadow-cyan-900'
}