"""empty message

Revision ID: 60073d80c127
Revises: 1d12bbbf5264
Create Date: 2023-07-29 10:38:29.772538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60073d80c127'
down_revision = '1d12bbbf5264'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('move', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accuracy', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('damage_class', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('effect_chance', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('effect_entry', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('flavor_text', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('power', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('stat_changes', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('target', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('move', schema=None) as batch_op:
        batch_op.drop_column('target')
        batch_op.drop_column('stat_changes')
        batch_op.drop_column('power')
        batch_op.drop_column('flavor_text')
        batch_op.drop_column('effect_entry')
        batch_op.drop_column('effect_chance')
        batch_op.drop_column('damage_class')
        batch_op.drop_column('accuracy')

    # ### end Alembic commands ###
