"""empty message

Revision ID: 71df552a5b8d
Revises: 1b2f81086ca7
Create Date: 2023-07-15 14:14:59.175960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71df552a5b8d'
down_revision = '1b2f81086ca7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('ability', sa.JSON(), nullable=True),
    sa.Column('base_experience', sa.Integer(), nullable=True),
    sa.Column('pokedex_id', sa.Integer(), nullable=True),
    sa.Column('hp_stat', sa.Integer(), nullable=True),
    sa.Column('attack_stat', sa.Integer(), nullable=True),
    sa.Column('defense_stat', sa.Integer(), nullable=True),
    sa.Column('special_attack_stat', sa.Integer(), nullable=True),
    sa.Column('special_defense_stat', sa.Integer(), nullable=True),
    sa.Column('speed_stat', sa.Integer(), nullable=True),
    sa.Column('pokemon_sprite', sa.String(), nullable=True),
    sa.Column('pokemon_type', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('token'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('team',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('pokemon_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team')
    op.drop_table('user')
    op.drop_table('pokemon')
    # ### end Alembic commands ###
